from typing import List


class SMBus:
    def __init__(self, bus: int | None = ...) -> None: ...

    def open(self, bus: int) -> None: ...
    def close(self) -> None: ...

    def read_byte(self, i2c_addr: int) -> int: ...
    def write_byte(self, i2c_addr: int, value: int) -> None: ...

    def read_byte_data(self, i2c_addr: int, register: int) -> int: ...
    def write_byte_data(self, i2c_addr: int, register: int, value: int) -> None: ...

    def read_word_data(self, i2c_addr: int, register: int) -> int: ...
    def write_word_data(self, i2c_addr: int, register: int, value: int) -> None: ...

    def read_i2c_block_data(
        self,
        i2c_addr: int,
        register: int,
        length: int = ...
    ) -> List[int]: ...

    def write_i2c_block_data(
        self,
        i2c_addr: int,
        register: int,
        data: List[int]
    ) -> None: ...

    def i2c_rdwr(self, *i2c_msgs) -> None: ...

    def __enter__(self) -> "SMBus": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...


class i2c_msg:
    @staticmethod
    def read(address: int, length: int) -> "i2c_msg": ...

    @staticmethod
    def write(address: int, data: bytes | List[int]) -> "i2c_msg": ...

    def __iter__(self): ...