class SpiDev:
    max_speed_hz: int
    mode: int
    bits_per_word: int
    lsbfirst: bool
    cshigh: bool
    loop: bool
    threewire: bool

    def open(self, bus: int, device: int) -> None: ...
    def close(self) -> None: ...
    def xfer(self, values: list[int]) -> list[int]: ...
    def xfer2(self, values: list[int]) -> list[int]: ...
    def xfer3(self, values: list[int]) -> list[int]: ...